# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from allgrpc.allproto import protos_pb2 as protos__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataManagementStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getDatabyPrompt = channel.unary_unary(
                '/vertor.DataManagement/getDatabyPrompt',
                request_serializer=protos__pb2.Request.SerializeToString,
                response_deserializer=protos__pb2.Response.FromString,
                _registered_method=True)
        self.updatabypath = channel.unary_unary(
                '/vertor.DataManagement/updatabypath',
                request_serializer=protos__pb2.Request.SerializeToString,
                response_deserializer=protos__pb2.Response.FromString,
                _registered_method=True)


class DataManagementServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getDatabyPrompt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updatabypath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataManagementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getDatabyPrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.getDatabyPrompt,
                    request_deserializer=protos__pb2.Request.FromString,
                    response_serializer=protos__pb2.Response.SerializeToString,
            ),
            'updatabypath': grpc.unary_unary_rpc_method_handler(
                    servicer.updatabypath,
                    request_deserializer=protos__pb2.Request.FromString,
                    response_serializer=protos__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vertor.DataManagement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vertor.DataManagement', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataManagement(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getDatabyPrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vertor.DataManagement/getDatabyPrompt',
            protos__pb2.Request.SerializeToString,
            protos__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def updatabypath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vertor.DataManagement/updatabypath',
            protos__pb2.Request.SerializeToString,
            protos__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
