# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'protos.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cprotos.proto\x12\x06vertor\"\x19\n\x07Request\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"\x1a\n\x08Response\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t2y\n\x0e\x44\x61taManagement\x12\x34\n\x0fgetDatabyPrompt\x12\x0f.vertor.Request\x1a\x10.vertor.Response\x12\x31\n\x0cupdatabypath\x12\x0f.vertor.Request\x1a\x10.vertor.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=24
  _globals['_REQUEST']._serialized_end=49
  _globals['_RESPONSE']._serialized_start=51
  _globals['_RESPONSE']._serialized_end=77
  _globals['_DATAMANAGEMENT']._serialized_start=79
  _globals['_DATAMANAGEMENT']._serialized_end=200
# @@protoc_insertion_point(module_scope)
