app:
  name: "qasystem"
  environment: "development"
  port: "8080"

jwt:
  secret_key: "qasystem"

ollama:
  name: "ollamaClient"
  host: "localhost"
  port: "11434"
  model: "gemma3:1b"

database:
  driver: mysql
  host: localhost
  port: 3306
  user: root
  password: mysql
  dbname: QASystem
  charset: utf8mb4
  parseTime: true
  loc: Local

nosqldatabase:
    host: localhost
    port: 27017
    databasename: "QASystem"
    collectionname: "userhistorymessage"